/**
 * message-types.js
 * Canonical runtime message constants.
 */

(function initMessageTypes(globalContext) {
    const AdvancedMessageTypes = Object.freeze({
        // reCAPTCHA
        RECAPTCHA_START_CAPTURE: 'RECAPTCHA_START_CAPTURE',
        RECAPTCHA_STOP_CAPTURE: 'RECAPTCHA_STOP_CAPTURE',
        RECAPTCHA_GET_CAPTURE_STATE: 'RECAPTCHA_GET_CAPTURE_STATE',

        // Akamai
        AKAMAI_START_CAPTURE: 'AKAMAI_START_CAPTURE',
        AKAMAI_STOP_CAPTURE: 'AKAMAI_STOP_CAPTURE',
        AKAMAI_GET_CAPTURE_STATE: 'AKAMAI_GET_CAPTURE_STATE',
        AKAMAI_CAPTURE_COMPLETED: 'AKAMAI_CAPTURE_COMPLETED',
        AKAMAI_EXTRACT_SENSOR: 'AKAMAI_EXTRACT_SENSOR',

        // Imperva
        IMPERVA_START_CAPTURE: 'IMPERVA_START_CAPTURE',
        IMPERVA_STOP_CAPTURE: 'IMPERVA_STOP_CAPTURE',
        IMPERVA_EXTRACT_SCRIPTS: 'IMPERVA_EXTRACT_SCRIPTS',
        IMPERVA_GET_CAPTURE_STATE: 'IMPERVA_GET_CAPTURE_STATE',
        IMPERVA_CAPTURE_COMPLETED: 'IMPERVA_CAPTURE_COMPLETED',

        // Shape Security
        SHAPESECURITY_START_CAPTURE: 'SHAPESECURITY_START_CAPTURE',
        SHAPESECURITY_STOP_CAPTURE: 'SHAPESECURITY_STOP_CAPTURE',
        SHAPESECURITY_GET_CAPTURE_STATE: 'SHAPESECURITY_GET_CAPTURE_STATE',
        SHAPESECURITY_CHECK_VERSION: 'SHAPESECURITY_CHECK_VERSION',
        SHAPESECURITY_START_EXTRACTION: 'SHAPESECURITY_START_EXTRACTION',

        // AWS WAF
        AWSWAF_START_ANALYSIS: 'AWSWAF_START_ANALYSIS',

        // Geetest
        GEETEST_CHECK_VERSION: 'GEETEST_CHECK_VERSION',
        GEETEST_ANALYZE_SCRIPTS: 'GEETEST_ANALYZE_SCRIPTS',

        // DataDome
        DATADOME_START_ANALYSIS: 'DATADOME_START_ANALYSIS',

        // Cloudflare
        CLOUDFLARE_START_ANALYSIS: 'CLOUDFLARE_START_ANALYSIS',

        // Turnstile
        TURNSTILE_START_ANALYSIS: 'TURNSTILE_START_ANALYSIS',

        // hCaptcha
        HCAPTCHA_START_ANALYSIS: 'HCAPTCHA_START_ANALYSIS',
        HCAPTCHA_CHECK_VERSION: 'HCAPTCHA_CHECK_VERSION',
        HCAPTCHA_START_CAPTURE: 'HCAPTCHA_START_CAPTURE',
        HCAPTCHA_STOP_CAPTURE: 'HCAPTCHA_STOP_CAPTURE',
        HCAPTCHA_GET_CAPTURE_STATE: 'HCAPTCHA_GET_CAPTURE_STATE',
        HCAPTCHA_CAPTURE_COMPLETED: 'HCAPTCHA_CAPTURE_COMPLETED',

        // FunCaptcha
        FUNCAPTCHA_START_ANALYSIS: 'FUNCAPTCHA_START_ANALYSIS',
        FUNCAPTCHA_START_CAPTURE: 'FUNCAPTCHA_START_CAPTURE',
        FUNCAPTCHA_STOP_CAPTURE: 'FUNCAPTCHA_STOP_CAPTURE',
        FUNCAPTCHA_GET_CAPTURE_STATE: 'FUNCAPTCHA_GET_CAPTURE_STATE',
        FUNCAPTCHA_CAPTURE_COMPLETED: 'FUNCAPTCHA_CAPTURE_COMPLETED'
    });

    globalContext.AdvancedMessageTypes = AdvancedMessageTypes;
})(typeof window !== 'undefined' ? window : (typeof self !== 'undefined' ? self : globalThis));
