/**
 * message-types.js
 * Canonical runtime message constants.
 */

(function initMessageTypes(globalContext) {
    const AdvancedMessageTypes = Object.freeze({
        // reCAPTCHA
        RECAPTCHA_START_CAPTURE: 'RECAPTCHA_START_CAPTURE',
        RECAPTCHA_STOP_CAPTURE: 'RECAPTCHA_STOP_CAPTURE',
        RECAPTCHA_GET_CAPTURE_STATE: 'RECAPTCHA_GET_CAPTURE_STATE',
        RECAPTCHA_GET_CAPTURE_RESULTS: 'RECAPTCHA_GET_CAPTURE_RESULTS',

        // Akamai
        AKAMAI_START_CAPTURE: 'AKAMAI_START_CAPTURE',
        AKAMAI_STOP_CAPTURE: 'AKAMAI_STOP_CAPTURE',
        AKAMAI_GET_CAPTURE_STATE: 'AKAMAI_GET_CAPTURE_STATE',
        AKAMAI_CAPTURE_COMPLETED: 'AKAMAI_CAPTURE_COMPLETED',
        AKAMAI_EXTRACT_SENSOR: 'AKAMAI_EXTRACT_SENSOR',
        AKAMAI_EXTRACTION_COMPLETED: 'AKAMAI_EXTRACTION_COMPLETED',
        AKAMAI_SHOW_ANALYZING_NOTIFICATION: 'AKAMAI_SHOW_ANALYZING_NOTIFICATION',
        AKAMAI_SHOW_EXTRACTING_NOTIFICATION: 'AKAMAI_SHOW_EXTRACTING_NOTIFICATION',

        // Imperva
        IMPERVA_START_CAPTURE: 'IMPERVA_START_CAPTURE',
        IMPERVA_STOP_CAPTURE: 'IMPERVA_STOP_CAPTURE',
        IMPERVA_EXTRACT_SCRIPTS: 'IMPERVA_EXTRACT_SCRIPTS',
        IMPERVA_GET_CAPTURE_STATE: 'IMPERVA_GET_CAPTURE_STATE',
        IMPERVA_CAPTURE_COMPLETED: 'IMPERVA_CAPTURE_COMPLETED',
        IMPERVA_SHOW_ANALYZING_NOTIFICATION: 'IMPERVA_SHOW_ANALYZING_NOTIFICATION',

        // Shape Security
        SHAPESECURITY_START_CAPTURE: 'SHAPESECURITY_START_CAPTURE',
        SHAPESECURITY_STOP_CAPTURE: 'SHAPESECURITY_STOP_CAPTURE',
        SHAPESECURITY_GET_CAPTURE_STATE: 'SHAPESECURITY_GET_CAPTURE_STATE',
        SHAPESECURITY_CHECK_HEADERS: 'SHAPESECURITY_CHECK_HEADERS',
        SHAPESECURITY_CHECK_COOKIES: 'SHAPESECURITY_CHECK_COOKIES',
        SHAPESECURITY_CHECK_VERSION: 'SHAPESECURITY_CHECK_VERSION',
        SHAPESECURITY_ANALYZE_SCRIPTS: 'SHAPESECURITY_ANALYZE_SCRIPTS',
        SHAPESECURITY_START_EXTRACTION: 'SHAPESECURITY_START_EXTRACTION',
        SHAPESECURITY_SHOW_ANALYZING_NOTIFICATION: 'SHAPESECURITY_SHOW_ANALYZING_NOTIFICATION',
        SHAPESECURITY_EXTRACTION_COMPLETED: 'SHAPESECURITY_EXTRACTION_COMPLETED',

        // AWS WAF
        AWSWAF_START_CAPTURE: 'AWSWAF_START_CAPTURE',
        AWSWAF_STOP_CAPTURE: 'AWSWAF_STOP_CAPTURE',
        AWSWAF_GET_STATE: 'AWSWAF_GET_STATE',
        AWSWAF_START_ANALYSIS: 'AWSWAF_START_ANALYSIS',
        AWSWAF_SHOW_ANALYZING_NOTIFICATION: 'AWSWAF_SHOW_ANALYZING_NOTIFICATION',

        // Geetest
        GEETEST_CHECK_VERSION: 'GEETEST_CHECK_VERSION',
        GEETEST_ANALYZE_SCRIPTS: 'GEETEST_ANALYZE_SCRIPTS',
        GEETEST_SHOW_VERSION_NOTIFICATION: 'GEETEST_SHOW_VERSION_NOTIFICATION',
        GEETEST_SHOW_ANALYZING_NOTIFICATION: 'GEETEST_SHOW_ANALYZING_NOTIFICATION',

        // DataDome
        DATADOME_START_ANALYSIS: 'DATADOME_START_ANALYSIS',
        DATADOME_SHOW_ANALYZING_NOTIFICATION: 'DATADOME_SHOW_ANALYZING_NOTIFICATION',

        // Cloudflare
        CLOUDFLARE_START_ANALYSIS: 'CLOUDFLARE_START_ANALYSIS',
        CLOUDFLARE_SHOW_ANALYZING_NOTIFICATION: 'CLOUDFLARE_SHOW_ANALYZING_NOTIFICATION',
        CLOUDFLARE_CHECK_VERSION: 'CLOUDFLARE_CHECK_VERSION',

        // Turnstile
        TURNSTILE_START_ANALYSIS: 'TURNSTILE_START_ANALYSIS',
        TURNSTILE_SHOW_ANALYZING_NOTIFICATION: 'TURNSTILE_SHOW_ANALYZING_NOTIFICATION',

        // hCaptcha
        HCAPTCHA_START_ANALYSIS: 'HCAPTCHA_START_ANALYSIS',
        HCAPTCHA_SHOW_ANALYZING_NOTIFICATION: 'HCAPTCHA_SHOW_ANALYZING_NOTIFICATION',
        HCAPTCHA_SHOW_VERSION_NOTIFICATION: 'HCAPTCHA_SHOW_VERSION_NOTIFICATION',
        HCAPTCHA_CHECK_VERSION: 'HCAPTCHA_CHECK_VERSION',
        HCAPTCHA_START_CAPTURE: 'HCAPTCHA_START_CAPTURE',
        HCAPTCHA_STOP_CAPTURE: 'HCAPTCHA_STOP_CAPTURE',
        HCAPTCHA_GET_CAPTURE_STATE: 'HCAPTCHA_GET_CAPTURE_STATE',
        HCAPTCHA_CAPTURE_COMPLETED: 'HCAPTCHA_CAPTURE_COMPLETED',

        // FunCaptcha
        FUNCAPTCHA_START_ANALYSIS: 'FUNCAPTCHA_START_ANALYSIS',
        FUNCAPTCHA_SHOW_ANALYZING_NOTIFICATION: 'FUNCAPTCHA_SHOW_ANALYZING_NOTIFICATION',
        FUNCAPTCHA_START_CAPTURE: 'FUNCAPTCHA_START_CAPTURE',
        FUNCAPTCHA_STOP_CAPTURE: 'FUNCAPTCHA_STOP_CAPTURE',
        FUNCAPTCHA_GET_CAPTURE_STATE: 'FUNCAPTCHA_GET_CAPTURE_STATE',
        FUNCAPTCHA_CAPTURE_COMPLETED: 'FUNCAPTCHA_CAPTURE_COMPLETED'
    });

    globalContext.AdvancedMessageTypes = AdvancedMessageTypes;
})(typeof window !== 'undefined' ? window : (typeof self !== 'undefined' ? self : globalThis));
